### PR TITLE
[enhancement] adds logging to preprocess

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
Firstly, I would like to give a big thank you, for inviting me :)
I would have some questions so feel free to give me your opinion:

a) should I open new branches in the future in this repo, or take the way over my own forked repo?
b) would you be more than happy to keep discussing stuff here?

Now to the main PR. I added some logging, so debugging is easier, and people can understand the preprocessor a little bit more.
For that I have added two new config parameters to the preprocessor 
  - `silent` which adds or removes logging completely 
  - `debug` which extends logging with more advanced config parameters.

It is a first start, and logging can get improved with more stuff over time.

I have structured the code in some color helper functions and added `chalk` as a dependency which is the most used easy logging solution, so color changing of text and adding new colors is quite easy. 

**If you wish to implement it natively with ANSI escape codes, I can change that, however it is easier to maintain with helper function. Also, if you would like to reduce the amount of color functions, I can collapse them into one, just let me know what code style you would prefer for this project. I am very happy to adapt to it.** 

I am marking this as a DRAFT PR, so we can get the code style and colors dialed in.

`silent: false, debug: false`
DevNoDebugCorrect
`silent: false, debug: false`
ProdNoDebugCorrect
`silent: false, debug: true`
DevDebugCorrect
`silent: false, debug: true`
ProdDebugCorrect
MissingEnv

### CODE REVIEW

**Comment by voorjaar** [comment]
Thank you for doing this. I think this pr is completely acceptable, you have a good aesthetic. Then, maybe the indentation can be smaller.

For pr, I think as long as it is not a destructive change, you can make it directly under main branch, but if it is a more dangerous change, you need to send a pull request, let me take a look. Is this okay for you?

**Comment by alexanderniebuhr** [comment]
@voorjaar that is fine. I like the work with you! Can I do the branches for the pr in this repo and do an internal pr, or do you want me to do it externally from my forked repo?

**Comment by voorjaar** [comment]
Yes, in most cases you can do the branches for the pr in this repo and do an internal pr.

**Comment by voorjaar** [comment]
I think it is more convenient for you.

**Comment by voorjaar** [comment]
But you can do whatever you like.

**Pull request merged**
